# Generated by Django 5.2.6 on 2025-10-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('individual', 'Jismoniy shaxs'), ('legal', 'Yuridik shaxs')], default='individual', max_length=255)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('modernation', 'Moderinizatsiya'), ('approved', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan ')], default='new', max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('payment_amount', models.PositiveBigIntegerField()),
                ('orgination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_student', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr')], max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('contract_amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor_of_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.BigIntegerField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_amounts', to='app.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_amounts', to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='app.university'),
        ),
    ]
